# SPDX-FileCopyrightText: 2024-2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: neochat
base: core24
adopt-info: neochat
grade: stable
confinement: strict
apps:
  neochat:
    extensions:
      - kde-neon-6
    command: usr/bin/neochat
    common-id: org.kde.neochat
    desktop: usr/share/applications/org.kde.neochat.desktop
    plugs:
      - home
      - removable-media
      - audio-playback
      - unity7
      - network
      - network-bind
      - network-manager-observe
      - password-manager-service
      - accounts-service
    environment:
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/plugins/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      QML_IMPORT_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml"

compression: lzo

package-repositories:
  - type: apt
    ppa: ubuntu-toolchain-r/test

slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.neochat
    bus: session

parts:
  olm:
    source: https://gitlab.matrix.org/matrix-org/olm.git
    source-depth: 1
    source-tag: '3.2.16'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/cmake

  libsecret:
    source: https://gitlab.gnome.org/GNOME/libsecret.git
    source-tag: '0.21.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dmanpage=false
      - -Dvapi=false
      - -Dintrospection=false
      - -Dcrypto=disabled
      - -Dgtk_doc=false
    build-packages:
      - meson
      - libglib2.0-dev
      - libgcrypt20-dev
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig

  qtkeychain:
    after: [libsecret]
    source: https://github.com/frankosterfeld/qtkeychain.git
    source-tag: 0.15.0
    source-depth: 1
    plugin: cmake
    build-environment:
      - PATH: /snap/bin:${PATH}
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TRANSLATIONS=NO
      - -DBUILD_WITH_QT6=ON
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/cmake

  libquotient:
    after:
      - olm
      - qtkeychain
    source: https://github.com/quotient-im/libQuotient.git
    source-tag: 0.9.5
    source-depth: 1
    plugin: cmake
    build-environment:
      - PATH: /snap/bin:${PATH}
    build-snaps:
      - cmake
    build-packages:
      - libssl-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
      - -DQuotient_ENABLE_E2EE=ON
      - -DBUILD_WITH_QT6=ON
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/cmake

  kquickimageeditor:
    source: https://invent.kde.org/libraries/kquickimageeditor.git
    source-tag: 'v0.3.0'
    source-depth: 1
    plugin: cmake
    build-environment:
      - PATH: /snap/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
      - LD_LIBRARY_PATH: "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/cmake

  kunifiedpush:
    source: https://invent.kde.org/libraries/kunifiedpush.git
    plugin: cmake
    build-environment:
      - PATH: /snap/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
      - LD_LIBRARY_PATH: "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF

  neochat:
    after:
      - qtkeychain
      - libquotient
      - kquickimageeditor
      - kunifiedpush
    parse-info:
      - usr/share/metainfo/org.kde.neochat.appdata.xml
    source: .
    plugin: cmake
    build-environment:
      - PATH: /snap/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
      - LD_LIBRARY_PATH: "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    build-packages:
      - cmark
      - duktape-dev
      - libcmark-dev
      - libsqlite3-dev
      - libvulkan-dev
      - libxkbcommon-dev
      - libicu-dev
      - libpulse0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/share/man

  deps:
    after: [neochat]
    plugin: nil
    stage-packages:
      - libcmark0.30.2
    prime:
      - usr/lib/*/libcmark.so*

  gpu-2404:
    after: [neochat]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
    
  cleanup:
    after:
      - neochat
    plugin: nil
    build-snaps:
      - core24
      - kde-qt6-core24-sdk/latest/edge
      - kf6-core24-sdk/latest/edge
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

